name: Automated PR Review

on:
  issues:
    types: [opened]

jobs:
  handle-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
       
      - name: Extract Issue Info
        id: issue
        run: |
          echo "ISSUE_TITLE=${{ github.event.issue.title }}" >> $GITHUB_ENV
          echo "ISSUE_BODY=${{ github.event.issue.body }}" >> $GITHUB_ENV
          echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
          
      - name: Send Issue to Devin
        run: |
          curl -X POST https://api.devin.ai/v1/sessions \
            -H "Authorization: Bearer $ {{ DEVIN_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{
            "repository": "${{ github.repository }}",
            "issue_number": "${{ env.ISSUE_NUMBER }}",
            "title": "${{ env.ISSUE_TITLE }}",
            "description": "${{ env.ISSUE_BODY }}",
            }" \

      - name: Comment on Issue
        uses: peter-evans/create-or-update-comment@v4
        with: 
          issue-number: ${{ env.ISSUE_NUMBER }}
          body: |
            Devin has picked up the issue
